version: "3.8"

services:
  symfony:
    build:
      context: ./docker/symfony
    volumes:
      - ./src:/var/www/html
    depends_on:
      - database

  database:
    build:
      context: ./docker/postgres
    environment:
      POSTGRES_DB: nom_de_la_base
      POSTGRES_USER: utilisateur
      POSTGRES_PASSWORD: mot_de_passe
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    build:
      context: ./docker/postgres
    depends_on:
      - database
    ports:
      - "8080:8080"

volumes:
  db_data:

networks:
  default:
    driver: bridge
