version: "3.8"

services:
  custom_composer:
    build:
      context: ./Docker/composer
    restart: unless-stopped
  
  custom_postgres:
    build:
        context: ./Docker/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-main}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mysecurepassword}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - justice

  custom_symfony:
    build:
      context: ./Docker/symfony
    depends_on:
      - custom_composer
      - custom_postgres
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-mysecurepassword}@custom_postgres:5432/${POSTGRES_DB:-main}?serverVersion=${POSTGRES_VERSION:-15.6}
    volumes:
      - ./src:/var/www/html
    ports:
      - 8000:8000
    networks:
      - justice
    restart: unless-stopped
    
  adminer:
    build:
      context: ./Docker/adminer
    depends_on:
      - custom_postgres
    ports:
      - "8080:8080"
    networks:
      - justice
  
volumes:
  db_data:

networks:
   justice:
    driver: bridge
