version: "3.8"
services:
  database:
    image: my-custom-postgres
    container_name: my-postgres-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres} # A modifier pour inclure le .env
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-test} # A modifier pour inclure le .env

volumes:
  pgdata: # Persister les données

networks:
  my-network:
    driver: bridge # Pour essayer de ce connecter a la database adminer avec comme hôte database
